export enum CVActionType {
    CV_POST_REQUEST = 'CV_POST_REQUEST',
    CV_POST_SUCCESS = 'CV_POST_SUCCESS',
    CV_POST_FAIL = 'CV_POST_FAIL',

    CV_GET_REQUEST = 'CV_GET_REQUEST',
    CV_GET_SUCCESS = 'CV_GET_SUCCESS',
    CV_GET_FAIL = 'CV_GET_FAIL',
};