export enum JobActionType {
    JOB_POST_REQUEST = 'JOB_POST_REQUEST',
    JOB_POST_SUCCESS = 'JOB_POST_SUCCESS',
    JOB_POST_FAIL = 'JOB_POST_FAIL',

    JOB_GET_REQUEST = 'JOB_GET_REQUEST',
    JOB_GET_SUCCESS = 'JOB_GET_SUCCESS',
    JOB_GET_FAIL = 'JOB_GET_FAIL',
};